// ===================== AVATARS =====================
const AVATARS = [
  { id:'fox',      emoji:'🦊', name:'Лисичка',
    greet: n=>`Хитрый план готов, ${n}! 🦊 Я Лисичка!`,
    sp:    n=>`Ты Лисичка 🦊 — хитрая весёлая лисичка-учитель. Говоришь с намёками, поддразниваешь. Коротко, весело. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'bear',     emoji:'🐻', name:'Мишка',
    greet: n=>`Уррр... Привет, ${n}! 🐻 Я Мишка!`,
    sp:    n=>`Ты Мишка 🐻 — добрый медлительный медведь. "Уффф...". Терпелив. Коротко, тепло. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'panda',    emoji:'🐼', name:'Панда',
    greet: n=>`Нихао, ${n}! 🐼 Я Панда!`,
    sp:    n=>`Ты Панда 🐼 — спокойная мудрая панда. Коротко, с достоинством. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'tiger',    emoji:'🐯', name:'Тигрёнок',
    greet: n=>`РЫЫ! Привет, ${n}! 🐯 Я Тигрёнок!`,
    sp:    n=>`Ты Тигрёнок 🐯 — энергичный смелый тигрёнок. "Вперёд!". Коротко, энергично. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'lion',     emoji:'🦁', name:'Лёвушка',
    greet: n=>`Я, Лёвушка, приветствую тебя, ${n}! 🦁`,
    sp:    n=>`Ты Лёвушка 🦁 — гордый благородный лев. "Достойный вопрос". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'elephant', emoji:'🐘', name:'Слонёнок',
    greet: n=>`Труу! Здравствуй, ${n}! 🐘 Я Слонёнок!`,
    sp:    n=>`Ты Слонёнок 🐘 — добрый умный слонёнок. "Я запомнил что...". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'bunny',    emoji:'🐰', name:'Зайка',
    greet: n=>`Прыг-скок, ${n}! 🐰 Я Зайка!`,
    sp:    n=>`Ты Зайка 🐰 — быстрая весёлая зайка. "Прыг!", "скок!". Коротко, быстро. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'penguin',  emoji:'🐧', name:'Пингви',
    greet: n=>`Кря! То есть... Привет, ${n}! 🐧 Я Пингви!`,
    sp:    n=>`Ты Пингви 🐧 — смешной пингвин. "Ой, то есть...". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'owl',      emoji:'🦉', name:'Совёнок',
    greet: n=>`Уху... Добро пожаловать, ${n}. 🦉 Я Совёнок.`,
    sp:    n=>`Ты Совёнок 🦉 — мудрый серьёзный совёнок. "Интересный факт:". Коротко, умно. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'cat',      emoji:'🐱', name:'Котёнок',
    greet: n=>`Мурр... Приветик, ${n}! 🐱 Я Котёнок!`,
    sp:    n=>`Ты Котёнок 🐱 — игривый ласковый котёнок. "Мурр...". Тёплый. Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'dog',      emoji:'🐶', name:'Щенок',
    greet: n=>`ГАВ-ГАВ! ${n}, привет! 🐶 Я Щенок!`,
    sp:    n=>`Ты Щенок 🐶 — верный восторженный щенок. "ОТЛИЧНО!", "гав!". Коротко, с энтузиазмом. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'frog',     emoji:'🐸', name:'Лягушка',
    greet: n=>`Ква-ква! Привет, ${n}! 🐸 Я Лягушка!`,
    sp:    n=>`Ты Лягушка 🐸 — весёлая лягушка. "Ква!". Коротко, задорно. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'koala',    emoji:'🐨', name:'Коала',
    greet: n=>`Ммм... Привет, ${n}... 🐨 Я Коала.`,
    sp:    n=>`Ты Коала 🐨 — спокойная сонная коала. "Мммм...". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'unicorn',  emoji:'🦄', name:'Единорог',
    greet: n=>`✨ Магия началась, ${n}! 🦄 Я Единорог!`,
    sp:    n=>`Ты Единорог 🦄 — волшебный восторженный единорог. "✨ магия языка...". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'dragon',   emoji:'🐲', name:'Дракончик',
    greet: n=>`РРРР! Слушай, ${n}! 🐲 Я Дракончик!`,
    sp:    n=>`Ты Дракончик 🐲 — грозный дракончик. "Докажи что умеешь!". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
  { id:'hamster',  emoji:'🐹', name:'Хомяк',
    greet: n=>`Хрум-хрум! Привет, ${n}! 🐹 Я Хомяк!`,
    sp:    n=>`Ты Хомяк 🐹 — запасливый суетливый хомяк. "Хрум!", "запасём это знание!". Коротко. Ученик 3 класса, имя: ${n}. Учишь английскому.` },
];

const PYTHON_TEACHER = {
  id:'python', emoji:'🐍', name:'Питон',
  greet: n=>`Привет, ${n}. 🐍 Я Питон — твой учитель информатики.`,
  sp:    n=>`Ты Питон 🐍 — строгий точный учитель информатики 7 класса. Краток. НЕ пиши готовый код — только объясняй логику. Ученик: ${n}.`
};

function currentTeacher(){ return currentSubject==='cs' ? PYTHON_TEACHER : (user?.avatar || AVATARS[0]); }

// ===================== ENGLISH MODULES =====================
const MODULES = [
  { id:1, title:"Hello, English!", icon:"👋", lessons:[
    {type:"mcq",question:"Как сказать «Привет»?",opts:[{t:"Hello",e:"👋"},{t:"Goodbye",e:"🚶"},{t:"Apple",e:"🍎"},{t:"Dog",e:"🐶"}],ans:0},
    {type:"mcq",question:"Как сказать «До свидания»?",opts:[{t:"Hello",e:"👋"},{t:"Goodbye",e:"🚶"},{t:"Please",e:"🙏"},{t:"Thank you",e:"😊"}],ans:1},
    {type:"truefalse",question:"Это красный цвет?",emoji:"🔴",answer:"Red",correctIs:true},
    {type:"truefalse",question:"Это синий цвет?",emoji:"🟢",answer:"Blue",correctIs:false},
    {type:"listen",word:"Apple",emoji:"🍎",opts:[{t:"Apple",e:"🍎"},{t:"Book",e:"📚"},{t:"Cat",e:"🐱"},{t:"Dog",e:"🐶"}],ans:0},
    {type:"fillgap",word:"HELLO",gapIdx:1,choices:["E","A","O"]},
    {type:"sentence",translation:"Привет, я [Имя]!",words:["Hello","I","am","Name"],correct:["Hello","I","am","Name"]},
    {type:"match",pairs:[{en:"Hello",ru:"Привет"},{en:"Goodbye",ru:"Пока"},{en:"Red",ru:"Красный"},{en:"Blue",ru:"Синий"}]},
  ]},
  { id:2, title:"My School", icon:"🏫", lessons:[
    {type:"mcq",question:"Что это?",img:"🎒",opts:[{t:"Schoolbag",e:"🎒"},{t:"Book",e:"📚"},{t:"Pen",e:"🖊️"},{t:"Ruler",e:"📏"}],ans:0},
    {type:"mcq",question:"Как сказать «Ручка»?",opts:[{t:"Pencil",e:"✏️"},{t:"Rubber",e:"🧽"},{t:"Pen",e:"🖊️"},{t:"Book",e:"📚"}],ans:2},
    {type:"truefalse",question:"Это карандаш (pencil)?",emoji:"✏️",answer:"Pencil",correctIs:true},
    {type:"listen",word:"Pencil",emoji:"✏️",opts:[{t:"Pen",e:"🖊️"},{t:"Pencil",e:"✏️"},{t:"Rubber",e:"🧽"},{t:"Book",e:"📚"}],ans:1},
    {type:"fillgap",word:"BOOK",gapIdx:2,choices:["O","A","U"]},
    {type:"sentence",translation:"Открой свою книгу!",words:["your","Open","book","please"],correct:["Open","your","book","please"]},
    {type:"match",pairs:[{en:"Book",ru:"Книга"},{en:"Pen",ru:"Ручка"},{en:"Pencil",ru:"Карандаш"},{en:"Bag",ru:"Сумка"}]},
    {type:"voice",word:"Open your book",translation:"Открой свою книгу"},
  ]},
  { id:3, title:"My Family", icon:"👨‍👩‍👧", lessons:[
    {type:"mcq",question:"Как сказать «Мама»?",opts:[{t:"Daddy",e:"👨"},{t:"Mummy",e:"👩"},{t:"Sister",e:"👧"},{t:"Brother",e:"👦"}],ans:1},
    {type:"mcq",question:"Как сказать «Брат»?",opts:[{t:"Mummy",e:"👩"},{t:"Sister",e:"👧"},{t:"Brother",e:"👦"},{t:"Daddy",e:"👨"}],ans:2},
    {type:"truefalse",question:"Это папа (daddy)?",emoji:"👨",answer:"Daddy",correctIs:true},
    {type:"listen",word:"Mummy",emoji:"👩",opts:[{t:"Daddy",e:"👨"},{t:"Mummy",e:"👩"},{t:"Brother",e:"👦"},{t:"Sister",e:"👧"}],ans:1},
    {type:"fillgap",word:"DADDY",gapIdx:2,choices:["D","T","B"]},
    {type:"sentence",translation:"Это моя мама",words:["my","This","is","mummy"],correct:["This","is","my","mummy"]},
    {type:"match",pairs:[{en:"Mummy",ru:"Мама"},{en:"Daddy",ru:"Папа"},{en:"Sister",ru:"Сестра"},{en:"Brother",ru:"Брат"}]},
    {type:"voice",word:"This is my mummy",translation:"Это моя мама"},
  ]},
  { id:4, title:"Weather", icon:"⛅", lessons:[
    {type:"mcq",question:"Как сказать «Солнечно»?",opts:[{t:"Raining",e:"🌧️"},{t:"Sunny",e:"☀️"},{t:"Snowing",e:"❄️"},{t:"Cloudy",e:"☁️"}],ans:1},
    {type:"truefalse",question:"Это солнечная погода?",emoji:"☀️",answer:"Sunny",correctIs:true},
    {type:"listen",word:"Sunny",emoji:"☀️",opts:[{t:"Raining",e:"🌧️"},{t:"Snowing",e:"❄️"},{t:"Sunny",e:"☀️"},{t:"Windy",e:"💨"}],ans:2},
    {type:"fillgap",word:"SUNNY",gapIdx:3,choices:["N","M","H"]},
    {type:"sentence",translation:"Сегодня солнечно",words:["sunny","It","today","is"],correct:["It","is","sunny","today"]},
    {type:"match",pairs:[{en:"Sunny",ru:"Солнечно"},{en:"Raining",ru:"Дождь"},{en:"Snowing",ru:"Снег"},{en:"Cold",ru:"Холодно"}]},
  ]},
  { id:5, title:"Free Time", icon:"⚽", lessons:[
    {type:"mcq",question:"Как сказать «Читать»?",opts:[{t:"Read",e:"📖"},{t:"Play",e:"⚽"},{t:"Swim",e:"🏊"},{t:"Dance",e:"💃"}],ans:0},
    {type:"truefalse",question:"Swim — это плавать?",emoji:"🏊",answer:"Swim = плавать",correctIs:true},
    {type:"listen",word:"Read",emoji:"📖",opts:[{t:"Write",e:"✍️"},{t:"Read",e:"📖"},{t:"Draw",e:"🎨"},{t:"Sing",e:"🎤"}],ans:1},
    {type:"fillgap",word:"PLAY",gapIdx:2,choices:["A","E","I"]},
    {type:"sentence",translation:"Я люблю плавать",words:["swim","I","to","like"],correct:["I","like","to","swim"]},
    {type:"match",pairs:[{en:"Read",ru:"Читать"},{en:"Play",ru:"Играть"},{en:"Swim",ru:"Плавать"},{en:"Dance",ru:"Танцевать"}]},
  ]},
  { id:6, title:"Health", icon:"🏥", lessons:[
    {type:"mcq",question:"Как сказать «Голова»?",opts:[{t:"Arm",e:"💪"},{t:"Leg",e:"🦵"},{t:"Head",e:"🤕"},{t:"Hand",e:"✋"}],ans:2},
    {type:"truefalse",question:"Это рука (hand)?",emoji:"✋",answer:"Hand",correctIs:true},
    {type:"listen",word:"Head",emoji:"🤕",opts:[{t:"Hand",e:"✋"},{t:"Leg",e:"🦵"},{t:"Head",e:"🤕"},{t:"Arm",e:"💪"}],ans:2},
    {type:"fillgap",word:"HAND",gapIdx:2,choices:["N","M","D"]},
    {type:"sentence",translation:"У меня болит голова",words:["head","My","hurts","aches"],correct:["My","head","hurts"]},
    {type:"match",pairs:[{en:"Head",ru:"Голова"},{en:"Hand",ru:"Рука"},{en:"Leg",ru:"Нога"},{en:"Arm",ru:"Плечо"}]},
  ]},
  { id:7, title:"Buildings", icon:"🏙️", lessons:[
    {type:"mcq",question:"Как сказать «Школа»?",opts:[{t:"Hospital",e:"🏥"},{t:"School",e:"🏫"},{t:"Shop",e:"🏪"},{t:"Park",e:"🌳"}],ans:1},
    {type:"truefalse",question:"Это парк (park)?",emoji:"🌳",answer:"Park",correctIs:true},
    {type:"listen",word:"School",emoji:"🏫",opts:[{t:"Hospital",e:"🏥"},{t:"Park",e:"🌳"},{t:"School",e:"🏫"},{t:"Shop",e:"🏪"}],ans:2},
    {type:"fillgap",word:"PARK",gapIdx:1,choices:["A","E","O"]},
    {type:"sentence",translation:"Я иду в школу",words:["to","I","school","go"],correct:["I","go","to","school"]},
    {type:"match",pairs:[{en:"School",ru:"Школа"},{en:"Hospital",ru:"Больница"},{en:"Park",ru:"Парк"},{en:"Shop",ru:"Магазин"}]},
  ]},
  { id:8, title:"My Holidays", icon:"✈️", lessons:[
    {type:"mcq",question:"Как сказать «Пляж»?",opts:[{t:"Mountain",e:"⛰️"},{t:"Forest",e:"🌲"},{t:"Beach",e:"🏖️"},{t:"City",e:"🌆"}],ans:2},
    {type:"truefalse",question:"Это горы (mountains)?",emoji:"⛰️",answer:"Mountains",correctIs:true},
    {type:"listen",word:"Beach",emoji:"🏖️",opts:[{t:"Mountain",e:"⛰️"},{t:"Beach",e:"🏖️"},{t:"Forest",e:"🌲"},{t:"City",e:"🌆"}],ans:1},
    {type:"fillgap",word:"BEACH",gapIdx:2,choices:["A","E","I"]},
    {type:"sentence",translation:"Я люблю каникулы",words:["love","I","my","holidays"],correct:["I","love","my","holidays"]},
    {type:"match",pairs:[{en:"Beach",ru:"Пляж"},{en:"Mountain",ru:"Гора"},{en:"Travel",ru:"Путешествие"},{en:"Holiday",ru:"Каникулы"}]},
  ]},
  { id:9, title:"Nature", icon:"🌿", lessons:[
    {type:"mcq",question:"Как сказать «Животное»?",opts:[{t:"Plant",e:"🌿"},{t:"Animal",e:"🐾"},{t:"Water",e:"💧"},{t:"Tree",e:"🌳"}],ans:1},
    {type:"truefalse",question:"Это тигр (tiger)?",emoji:"🐯",answer:"Tiger",correctIs:true},
    {type:"listen",word:"Tiger",emoji:"🐯",opts:[{t:"Lion",e:"🦁"},{t:"Tiger",e:"🐯"},{t:"Bear",e:"🐻"},{t:"Wolf",e:"🐺"}],ans:1},
    {type:"fillgap",word:"TIGER",gapIdx:2,choices:["G","T","K"]},
    {type:"sentence",translation:"Берегите природу!",words:["nature","Protect","our","please"],correct:["Protect","our","nature"]},
    {type:"match",pairs:[{en:"Tiger",ru:"Тигр"},{en:"Forest",ru:"Лес"},{en:"Animal",ru:"Животное"},{en:"Nature",ru:"Природа"}]},
  ]},
];

// ===================== CS MODULES (Python) =====================
const CS_MODULES = [
  { id:1, title:"Знакомство с Python", icon:"🐍", par:"§18", lessons:[
    {type:"mcq",question:"Какая команда выводит текст на экран?",opts:[{t:"print()",e:"📤"},{t:"show()",e:"👁️"},{t:"write()",e:"✏️"},{t:"display()",e:"🖥️"}],ans:0},
    {type:"mcq",question:"Что напечатает: print(5 + 3)?",opts:[{t:"5 + 3",e:"📝"},{t:"8",e:"8️⃣"},{t:"53",e:"🔢"},{t:"Ошибка",e:"💥"}],ans:1},
    {type:"truefalse",question:"print('Привет') выведет слово Привет?",emoji:"📤",answer:"Да, print выводит текст",correctIs:true},
    {type:"fillgap",word:"PRINT",gapIdx:0,choices:["P","B","F"]},
    {type:"match",pairs:[{en:"print()",ru:"Вывод на экран"},{en:"#",ru:"Комментарий"},{en:"+",ru:"Сложение"},{en:"*",ru:"Умножение"}]},
  ]},
  { id:2, title:"Переменные", icon:"📦", par:"§19", lessons:[
    {type:"mcq",question:"Как сохранить число 10 в переменную x?",opts:[{t:"x == 10",e:"❌"},{t:"x = 10",e:"✅"},{t:"x := 10",e:"❌"},{t:"int x = 10",e:"❌"}],ans:1},
    {type:"mcq",question:"Что делает input()?",opts:[{t:"Выводит текст",e:"📤"},{t:"Считывает ввод",e:"📥"},{t:"Считает сумму",e:"➕"},{t:"Открывает файл",e:"📂"}],ans:1},
    {type:"truefalse",question:"input() всегда возвращает строку?",emoji:"📥",answer:"Да! input() = строка",correctIs:true},
    {type:"fillgap",word:"INPUT",gapIdx:0,choices:["I","O","U"]},
    {type:"match",pairs:[{en:"x = 5",ru:"Переменная x = 5"},{en:"input()",ru:"Ввод от пользователя"},{en:"int()",ru:"Строка → число"},{en:"str()",ru:"Число → строка"}]},
  ]},
  { id:3, title:"if / else", icon:"🔀", par:"§20-21", lessons:[
    {type:"mcq",question:"Что ставится в конце строки if?",opts:[{t:"Точка .",e:"."},{t:"Двоеточие :",e:":"},{t:"Скобка )",e:")"},{t:"Точка с запятой ;",e:";"}],ans:1},
    {type:"truefalse",question:"else выполняется когда условие if ЛОЖНО?",emoji:"🔀",answer:"else = иначе",correctIs:true},
    {type:"truefalse",question:"elif — это то же самое что else if?",emoji:"🤔",answer:"Да! elif = else if",correctIs:true},
    {type:"fillgap",word:"ELSE",gapIdx:0,choices:["E","A","I"]},
    {type:"match",pairs:[{en:"if",ru:"Если"},{en:"elif",ru:"Иначе если"},{en:"else",ru:"Иначе"},{en:":",ru:"Начало блока кода"}]},
  ]},
  { id:4, title:"Сравнение", icon:"⚖️", par:"§22-23", lessons:[
    {type:"mcq",question:"Что означает == в Python?",opts:[{t:"Присваивание",e:"="},{t:"Сравнение равенства",e:"⚖️"},{t:"Больше",e:">"},{t:"Меньше",e:"<"}],ans:1},
    {type:"truefalse",question:"3 != 5 означает: 3 НЕ равно 5?",emoji:"≠",answer:"!= означает не равно",correctIs:true},
    {type:"truefalse",question:"True and False равно True?",emoji:"🤔",answer:"False! Оба должны быть True",correctIs:false},
    {type:"fillgap",word:"TRUE",gapIdx:0,choices:["T","F","R"]},
    {type:"match",pairs:[{en:"==",ru:"Равно"},{en:"!=",ru:"Не равно"},{en:"and",ru:"И (оба true)"},{en:"or",ru:"ИЛИ (хоть один)"}]},
  ]},
  { id:5, title:"Файлы", icon:"📁", par:"§24-25", lessons:[
    {type:"mcq",question:"Какая функция открывает файл?",opts:[{t:"open()",e:"📂"},{t:"read()",e:"📖"},{t:"start()",e:"▶️"},{t:"load()",e:"💾"}],ans:0},
    {type:"truefalse",question:"f.close() закрывает файл?",emoji:"🔒",answer:"Да! Всегда закрывай файл",correctIs:true},
    {type:"fillgap",word:"OPEN",gapIdx:0,choices:["O","A","E"]},
    {type:"match",pairs:[{en:"'r'",ru:"Чтение файла"},{en:"'w'",ru:"Запись (с нуля)"},{en:"'a'",ru:"Добавить в конец"},{en:".read()",ru:"Прочитать файл"}]},
  ]},
  { id:6, title:"Цикл while", icon:"🔁", par:"§28-29", lessons:[
    {type:"mcq",question:"i=0, while i<3: i+=1. Сколько раз выполнится?",opts:[{t:"2",e:"2️⃣"},{t:"3",e:"3️⃣"},{t:"4",e:"4️⃣"},{t:"0",e:"0️⃣"}],ans:1},
    {type:"truefalse",question:"while True: создаёт бесконечный цикл?",emoji:"♾️",answer:"Да! True всегда истина",correctIs:true},
    {type:"fillgap",word:"WHILE",gapIdx:0,choices:["W","V","M"]},
    {type:"match",pairs:[{en:"while",ru:"Цикл пока условие верно"},{en:"break",ru:"Выйти из цикла"},{en:"continue",ru:"Пропустить шаг"},{en:"i += 1",ru:"i = i + 1"}]},
  ]},
  { id:7, title:"for и range", icon:"🔄", par:"§30-31", lessons:[
    {type:"mcq",question:"for i in range(3): print(i). Что напечатает?",opts:[{t:"1 2 3",e:"1️⃣"},{t:"0 1 2",e:"0️⃣"},{t:"3",e:"3️⃣"},{t:"Ошибка",e:"💥"}],ans:1},
    {type:"truefalse",question:"range(5) начинается с 0?",emoji:"0️⃣",answer:"Да! range(5) = 0,1,2,3,4",correctIs:true},
    {type:"fillgap",word:"FOR",gapIdx:0,choices:["F","G","T"]},
    {type:"match",pairs:[{en:"range(5)",ru:"0 1 2 3 4"},{en:"range(1,4)",ru:"1 2 3"},{en:"for i in ...",ru:"Цикл по каждому"},{en:"len(lst)",ru:"Длина списка"}]},
  ]},
  { id:8, title:"Функции", icon:"🔧", par:"§32-34", lessons:[
    {type:"mcq",question:"Как объявить функцию greet?",opts:[{t:"function greet():",e:"❌"},{t:"def greet():",e:"✅"},{t:"func greet():",e:"❌"},{t:"greet = function:",e:"❌"}],ans:1},
    {type:"truefalse",question:"def нужно писать при КАЖДОМ вызове функции?",emoji:"🔧",answer:"Нет! def только при объявлении",correctIs:false},
    {type:"fillgap",word:"DEF",gapIdx:0,choices:["D","B","P"]},
    {type:"match",pairs:[{en:"def",ru:"Объявить функцию"},{en:"return",ru:"Вернуть значение"},{en:"()",ru:"Скобки параметров"},{en:"fn()",ru:"Вызов функции"}]},
  ]},
];
